// clients/lit/src/a2ui-renderer.ts
import { LitElement, html, css, PropertyValues } from 'lit';

interface A2UIComponent {
  id: string;
  Column?: { children: string[] };
  Row?: { children: string[] };
  Card?: { child: string };
  Text?: { text?: string; dataBinding?: { path: string } };
  TextField?: { label?: string; placeholder?: string; dataBinding?: { path: string } };
  Button?: { text: string; action: { type: string; data?: Record<string, any> } };
}

interface A2UIMessage {
  beginRendering?: { surfaceId: string; root: string };
  surfaceUpdate?: { surfaceId: string; components: A2UIComponent[] };
  dataModelUpdate?: { surfaceId: string; contents: Record<string, any> };
}

export class A2UIRenderer extends LitElement {
  static styles = css`
    :host { display: block; font-family: system-ui, sans-serif; }
    .column { display: flex; flex-direction: column; gap: 10px; }
    .row { display: flex; flex-direction: row; gap: 10px; }
    .card {
      background: white;
      border: 1px solid #ddd;
      border-radius: 8px;
      padding: 20px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    .card.success { background: #d4edda; border-color: #c3e6cb; }
    .text { margin: 5px 0; }
    .text.header { font-size: 24px; font-weight: bold; margin-bottom: 15px; }
    .text.title { font-size: 20px; color: #155724; }
    .field { margin-bottom: 15px; }
    .field label { display: block; margin-bottom: 5px; font-weight: 500; }
    .field input {
      width: 100%;
      padding: 10px;
      border: 1px solid #ddd;
      border-radius: 4px;
      font-size: 16px;
      box-sizing: border-box;
    }
    button {
      background: #007bff;
      color: white;
      border: none;
      padding: 12px 24px;
      border-radius: 4px;
      cursor: pointer;
      font-size: 16px;
      width: 100%;
    }
    button:hover { background: #0056b3; }
    .loading { padding: 20px; color: #666; }
  `;

  static properties = {
    streamUrl: { type: String },
    baseUrl: { type: String },
    loading: { state: true },
    surfaceId: { state: true },
    rootId: { state: true },
    components: { state: true },
    dataModel: { state: true },
  };

  streamUrl = '';
  baseUrl = 'http://localhost:8080';
  loading = true;
  surfaceId = '';
  rootId = 'root';
  components: Record<string, A2UIComponent> = {};
  dataModel: Record<string, any> = {};
  formData: Record<string, any> = {};

  connectedCallback() {
    super.connectedCallback();
    if (this.streamUrl) {
      this.loadSurface(this.streamUrl);
    }
  }

  async loadSurface(url: string) {
    this.loading = true;
    const response = await fetch(url);
    const text = await response.text();
    const messages: A2UIMessage[] = text
      .split('\n')
      .filter(line => line.trim())
      .map(line => JSON.parse(line));
    this.processMessages(messages);
    this.loading = false;
  }

  processMessages(messages: A2UIMessage[]) {
    const comps: Record<string, A2UIComponent> = {};
    let data: Record<string, any> = {};

    for (const msg of messages) {
      if (msg.beginRendering) {
        this.surfaceId = msg.beginRendering.surfaceId;
        this.rootId = msg.beginRendering.root;
      }
      if (msg.surfaceUpdate) {
        for (const comp of msg.surfaceUpdate.components) {
          comps[comp.id] = comp;
        }
      }
      if (msg.dataModelUpdate) {
        data = { ...data, ...msg.dataModelUpdate.contents };
      }
    }

    this.components = comps;
    this.dataModel = data;

    // Initialize form data
    for (const [path, value] of Object.entries(data)) {
      if (path.startsWith('/form/')) {
        this.formData[path] = value;
      }
    }
  }

  getData(path?: string): any {
    if (!path) return '';
    return this.formData[path] ?? this.dataModel[path] ?? '';
  }

  handleInput(path: string, e: Event) {
    this.formData[path] = (e.target as HTMLInputElement).value;
  }

  async handleAction(action: { type: string; data?: Record<string, any> }) {
    if (action.type === 'submit' && action.data?.endpoint) {
      const event = {
        event: {
          surfaceId: this.surfaceId,
          componentId: 'submit-btn',
          type: 'action',
          data: {
            name: this.formData['/form/name'] || '',
            date: this.formData['/form/date'] || '',
            time: this.formData['/form/time'] || '',
            party: parseInt(this.formData['/form/party']) || 2
          }
        }
      };

      this.loading = true;
      const endpoint = this.baseUrl + action.data.endpoint;
      const response = await fetch(endpoint, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(event)
      });
      const text = await response.text();
      const messages = text.split('\n').filter(l => l.trim()).map(l => JSON.parse(l));
      this.processMessages(messages);
      this.loading = false;
    }
    else if (action.type === 'navigate' && action.data?.url) {
      await this.loadSurface(this.baseUrl + action.data.url);
    }
  }

  renderComponent(id: string): any {
    const comp = this.components[id];
    if (!comp) return html``;

    if (comp.Column) {
      return html`
        <div class="column">
          ${comp.Column.children.map(childId => this.renderComponent(childId))}
        </div>
      `;
    }

    if (comp.Row) {
      return html`
        <div class="row">
          ${comp.Row.children.map(childId => this.renderComponent(childId))}
        </div>
      `;
    }

    if (comp.Card) {
      return html`
        <div class="card ${id.includes('success') ? 'success' : ''}">
          ${this.renderComponent(comp.Card.child)}
        </div>
      `;
    }

    if (comp.Text) {
      const text = comp.Text.text || this.getData(comp.Text.dataBinding?.path);
      const classes = `text ${id === 'header' ? 'header' : ''} ${id === 'title' ? 'title' : ''}`;
      return html`<div class="${classes}">${text}</div>`;
    }

    if (comp.TextField) {
      const path = comp.TextField.dataBinding?.path || '';
      return html`
        <div class="field">
          <label>${comp.TextField.label}</label>
          <input
            .value="${this.getData(path)}"
            placeholder="${comp.TextField.placeholder || ''}"
            @input="${(e: Event) => this.handleInput(path, e)}"
          />
        </div>
      `;
    }

    if (comp.Button) {
      return html`
        <button @click="${() => this.handleAction(comp.Button!.action)}">
          ${comp.Button.text}
        </button>
      `;
    }

    return html``;
  }

  render() {
    if (this.loading) {
      return html`<div class="loading">Loading...</div>`;
    }
    return this.renderComponent(this.rootId);
  }
}

customElements.define('a2ui-renderer', A2UIRenderer);

// clients/angular/src/app/a2ui-renderer.component.ts
import { Component, Input, OnInit, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { A2UIService, A2UIMessage, A2UIComponent, ClientEvent } from './a2ui.service';

@Component({
  selector: 'a2ui-renderer',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="a2ui-surface">
      @if (loading()) {
        <div class="loading">Loading...</div>
      } @else {
        <ng-container *ngTemplateOutlet="componentTpl; context: { id: rootId() }"></ng-container>
      }
    </div>

    <ng-template #componentTpl let-id="id">
      @if (getComponent(id); as comp) {
        <!-- Column -->
        @if (comp.Column) {
          <div class="a2ui-column">
            @for (childId of comp.Column.children; track childId) {
              <ng-container *ngTemplateOutlet="componentTpl; context: { id: childId }"></ng-container>
            }
          </div>
        }

        <!-- Row -->
        @if (comp.Row) {
          <div class="a2ui-row">
            @for (childId of comp.Row.children; track childId) {
              <ng-container *ngTemplateOutlet="componentTpl; context: { id: childId }"></ng-container>
            }
          </div>
        }

        <!-- Card -->
        @if (comp.Card) {
          <div class="a2ui-card" [class.success]="id.includes('success')">
            <ng-container *ngTemplateOutlet="componentTpl; context: { id: comp.Card.child }"></ng-container>
          </div>
        }

        <!-- Text -->
        @if (comp.Text) {
          <div class="a2ui-text"
               [class.header]="id === 'header'"
               [class.title]="id === 'title'">
            {{ comp.Text.text || getData(comp.Text.dataBinding?.path) }}
          </div>
        }

        <!-- TextField -->
        @if (comp.TextField) {
          <div class="a2ui-field">
            <label>{{ comp.TextField.label }}</label>
            <input
              [placeholder]="comp.TextField.placeholder || ''"
              [ngModel]="getData(comp.TextField.dataBinding?.path)"
              (ngModelChange)="setFormData(comp.TextField.dataBinding?.path, $event)"
            />
          </div>
        }

        <!-- Button -->
        @if (comp.Button) {
          <button class="a2ui-button" (click)="handleAction(comp.Button.action)">
            {{ comp.Button.text }}
          </button>
        }
      }
    </ng-template>
  `,
  styles: [`
    .a2ui-surface { font-family: system-ui, sans-serif; }
    .a2ui-column { display: flex; flex-direction: column; gap: 10px; }
    .a2ui-row { display: flex; flex-direction: row; gap: 10px; }
    .a2ui-card {
      background: white;
      border: 1px solid #ddd;
      border-radius: 8px;
      padding: 20px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    .a2ui-card.success { background: #d4edda; border-color: #c3e6cb; }
    .a2ui-text { margin: 5px 0; }
    .a2ui-text.header { font-size: 24px; font-weight: bold; margin-bottom: 15px; }
    .a2ui-text.title { font-size: 20px; color: #155724; }
    .a2ui-field { margin-bottom: 15px; }
    .a2ui-field label { display: block; margin-bottom: 5px; font-weight: 500; }
    .a2ui-field input {
      width: 100%;
      padding: 10px;
      border: 1px solid #ddd;
      border-radius: 4px;
      font-size: 16px;
      box-sizing: border-box;
    }
    .a2ui-button {
      background: #007bff;
      color: white;
      border: none;
      padding: 12px 24px;
      border-radius: 4px;
      cursor: pointer;
      font-size: 16px;
      width: 100%;
    }
    .a2ui-button:hover { background: #0056b3; }
    .loading { padding: 20px; color: #666; }
  `]
})
export class A2UIRendererComponent implements OnInit {
  @Input() streamUrl = '';
  @Input() baseUrl = 'http://localhost:8080';

  private a2uiService = new A2UIService();

  loading = signal(true);
  surfaceId = signal('');
  rootId = signal('root');
  components = signal<Record<string, A2UIComponent>>({});
  dataModel = signal<Record<string, any>>({});
  formData: Record<string, any> = {};

  async ngOnInit() {
    if (this.streamUrl) {
      await this.loadSurface(this.streamUrl);
    }
  }

  async loadSurface(url: string) {
    this.loading.set(true);
    const messages = await this.a2uiService.fetchSurface(url);
    this.processMessages(messages);
    this.loading.set(false);
  }

  processMessages(messages: A2UIMessage[]) {
    const comps: Record<string, A2UIComponent> = {};
    let data: Record<string, any> = {};

    for (const msg of messages) {
      if (msg.beginRendering) {
        this.surfaceId.set(msg.beginRendering.surfaceId);
        this.rootId.set(msg.beginRendering.root);
      }
      if (msg.surfaceUpdate) {
        for (const comp of msg.surfaceUpdate.components) {
          comps[comp.id] = comp;
        }
      }
      if (msg.dataModelUpdate) {
        data = { ...data, ...msg.dataModelUpdate.contents };
      }
    }

    this.components.set(comps);
    this.dataModel.set(data);

    // Initialize form data from data model
    for (const [path, value] of Object.entries(data)) {
      if (path.startsWith('/form/')) {
        this.formData[path] = value;
      }
    }
  }

  getComponent(id: string): A2UIComponent | undefined {
    return this.components()[id];
  }

  getData(path?: string): any {
    if (!path) return '';
    return this.formData[path] ?? this.dataModel()[path] ?? '';
  }

  setFormData(path: string | undefined, value: any) {
    if (path) {
      this.formData[path] = value;
    }
  }

  async handleAction(action: { type: string; data?: Record<string, any> }) {
    if (action.type === 'submit' && action.data?.['endpoint']) {
      const event: ClientEvent = {
        event: {
          surfaceId: this.surfaceId(),
          componentId: 'submit-btn',
          type: 'action',
          data: {
            name: this.formData['/form/name'] || '',
            date: this.formData['/form/date'] || '',
            time: this.formData['/form/time'] || '',
            party: parseInt(this.formData['/form/party']) || 2
          }
        }
      };

      try {
        this.loading.set(true);
        const endpoint = this.baseUrl + action.data['endpoint'];
        const messages = await this.a2uiService.sendEvent(endpoint, event);
        this.processMessages(messages);
      } catch (error) {
        console.error('Submit failed:', error);
        alert('Submit failed - check console');
      } finally {
        this.loading.set(false);
      }
    }
    else if (action.type === 'navigate' && action.data?.['url']) {
      await this.loadSurface(this.baseUrl + action.data['url']);
    }
  }
}
